// Code generated by "stringer -type=DW_EH_PE_basicType,DW_EH_PE_modType -output eh_frame_model_string.go"; DO NOT EDIT.

package macho_widgets

import "fmt"

const (
	_DW_EH_PE_basicType_name_0 = "DW_EH_PE_ptrDW_EH_PE_uleb128DW_EH_PE_udata2DW_EH_PE_udata4DW_EH_PE_udata8"
	_DW_EH_PE_basicType_name_1 = "DW_EH_PE_signedDW_EH_PE_sleb128DW_EH_PE_sdata2DW_EH_PE_sdata4DW_EH_PE_sdata8"
)

var (
	_DW_EH_PE_basicType_index_0 = [...]uint8{0, 12, 28, 43, 58, 73}
	_DW_EH_PE_basicType_index_1 = [...]uint8{0, 15, 31, 46, 61, 76}
)

func (i DW_EH_PE_basicType) String() string {
	switch {
	case 0 <= i && i <= 4:
		return _DW_EH_PE_basicType_name_0[_DW_EH_PE_basicType_index_0[i]:_DW_EH_PE_basicType_index_0[i+1]]
	case 8 <= i && i <= 12:
		i -= 8
		return _DW_EH_PE_basicType_name_1[_DW_EH_PE_basicType_index_1[i]:_DW_EH_PE_basicType_index_1[i+1]]
	default:
		return fmt.Sprintf("DW_EH_PE_basicType(%d)", i)
	}
}

const (
	_DW_EH_PE_modType_name_0 = "DW_EH_PE_absptr"
	_DW_EH_PE_modType_name_1 = "DW_EH_PE_pcrel"
	_DW_EH_PE_modType_name_2 = "DW_EH_PE_textrel"
	_DW_EH_PE_modType_name_3 = "DW_EH_PE_datarel"
	_DW_EH_PE_modType_name_4 = "DW_EH_PE_funcrel"
	_DW_EH_PE_modType_name_5 = "DW_EH_PE_aligned"
)

var (
	_DW_EH_PE_modType_index_0 = [...]uint8{0, 15}
	_DW_EH_PE_modType_index_1 = [...]uint8{0, 14}
	_DW_EH_PE_modType_index_2 = [...]uint8{0, 16}
	_DW_EH_PE_modType_index_3 = [...]uint8{0, 16}
	_DW_EH_PE_modType_index_4 = [...]uint8{0, 16}
	_DW_EH_PE_modType_index_5 = [...]uint8{0, 16}
)

func (i DW_EH_PE_modType) String() string {
	switch {
	case i == 0:
		return _DW_EH_PE_modType_name_0
	case i == 16:
		return _DW_EH_PE_modType_name_1
	case i == 32:
		return _DW_EH_PE_modType_name_2
	case i == 48:
		return _DW_EH_PE_modType_name_3
	case i == 64:
		return _DW_EH_PE_modType_name_4
	case i == 80:
		return _DW_EH_PE_modType_name_5
	default:
		return fmt.Sprintf("DW_EH_PE_modType(%d)", i)
	}
}
